[theme]
# Primary color for elements (e.g., buttons, highlights)
primaryColor = "#2196f3"  # Bright blue for a fresh and modern touch

# Dark background for the main content area (Elegant and easy on the eyes)
backgroundColor = "#1c1c1c"  # Very dark gray for a deeper, subtle background

# Sidebar background color (Slightly lighter for contrast)
secondaryBackgroundColor = "#333333"  # Medium dark gray for the sidebar

# Text color for improved readability
textColor = "#e0e0e0"  # Light gray text for less harsh contrast on dark background

# Font settings
font = "Roboto, sans-serif"  # Modern, sleek font for a clean look
